# MultiForge production Ed25519 license verification public keys.
# One line per key: <kid>=<base64url raw 32-byte public key>
# The private key MUST NOT live in this repository.
#
# Production keys used to verify customer license tokens at server boot.
multiforge-prod-2026-1=GF0sRoku3-w7ge5peZ2Y-x1cfkzgDflrl-OQKYbxC1Y
